name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3

      - name: Database setup
        run: |
          bin/rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: |
          bin/rails test
